### ISSUE TITLE
Issue with i1Profiler.pkg.recipe when using new download Sparkle Feed

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/mosen-recipes#47]
Using the newer version pulled from the updated Sparkle Feed URL from #46, the PKG recipe now fails as per the below:

```
FileCreator
{'Input': {'file_content': '#!/bin/bash\n'
                           '\n'
                           'echo "postinstall script start******"\n'
                           'pwd\n'
                           'ls \n'
                           '# autopkg: do not run applet to append loginitem\n'
                           '# autopkg: TODO - may need to create a LaunchItem '
                           'to replace modification of login items\n'
                           '# TODO: only launch app if install is without '
                           'logout\n'
                           '#echo "Launching the app"\n'
                           '#open /Applications/i1Profiler/i1ProfilerTray.app\n'
                           'echo "Return Code:"\n'
                           'echo $?\n'
                           'echo "postinstall script end******"\n',
           'file_path': '/Users/darren/Library/AutoPkg/Cache/com.github.mosen.pkg.i1Profiler/i1Profiler/pkgroot/i1ProfilerTrayComponent.pkg/Scripts/postinstall'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/FileCreator.py", line 41, in main
    with open(self.env["file_path"], "w") as fileref:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/darren/Library/AutoPkg/Cache/com.github.mosen.pkg.i1Profiler/i1Profiler/pkgroot/i1ProfilerTrayComponent.pkg/Scripts/postinstall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 676, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 483, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/FileCreator.py", line 45, in main
    raise ProcessorError(f"Can't create file at {self.env['file_path']}: {err}")
autopkglib.ProcessorError: Can't create file at /Users/darren/Library/AutoPkg/Cache/com.github.mosen.pkg.i1Profiler/i1Profiler/pkgroot/i1ProfilerTrayComponent.pkg/Scripts/postinstall: [Errno 2] No such file or directory: '/Users/darren/Library/AutoPkg/Cache/com.github.mosen.pkg.i1Profiler/i1Profiler/pkgroot/i1ProfilerTrayComponent.pkg/Scripts/postinstall'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 676, in process
    self.env = processor.process()
Can't create file at /Users/darren/Library/AutoPkg/Cache/com.github.mosen.pkg.i1Profiler/i1Profiler/pkgroot/i1ProfilerTrayComponent.pkg/Scripts/postinstall: [Errno 2] No such file or directory: '/Users/darren/Library/AutoPkg/Cache/com.github.mosen.pkg.i1Profiler/i1Profiler/pkgroot/i1ProfilerTrayComponent.pkg/Scripts/postinstall'
Failed.
Receipt written to /Users/darren/Library/AutoPkg/Cache/com.github.mosen.pkg.i1Profiler/receipts/i1Profiler.pkg-receipt-20200918-103436.plist

The following recipes failed:
    /Users/darren/Library/AutoPkg/RecipeRepos/com.github.autopkg.mosen-recipes/XRite/i1Profiler.pkg.recipe
        Error in com.github.mosen.pkg.i1Profiler: Processor: FileCreator: Error: Can't create file at /Users/darren/Library/AutoPkg/Cache/com.github.mosen.pkg.i1Profiler/i1Profiler/pkgroot/i1ProfilerTrayComponent.pkg/Scripts/postinstall: [Errno 2] No such file or directory: '/Users/darren/Library/AutoPkg/Cache/com.github.mosen.pkg.i1Profiler/i1Profiler/pkgroot/i1ProfilerTrayComponent.pkg/Scripts/postinstall'
```

Looking at the pulled apart installer package, the package "i1ProfilerTrayComponent.pkg" is no longer included. I've reviewed the other packages for scripts and can't find any mention of an AppleScript line that the above was disabling. 

I'd like a second opinion but it seems the AppleScript commands from the i1Profiler team are no longer included and we might be able to gut the majority of the work out of the PKG recipe?

**Comment by Daz-wallace** [comment]
The parent PR was pulled in, but I was wonder if anyone has an opinion on the above?

Ta 😊

**Comment by macmule** [comment]
Looks like this issue can be closed:

```
                           'receipts': [{'installed_size': 0,
                                         'packageid': 'com.xrite.i1profiler.EZColor.pkg',
                                         'version': '1.0'},
                                        {'installed_size': 33694,
                                         'packageid': 'com.xrite.xritedeviceservices.installer.pkg',
                                         'version': '3.0.128.9167'},
                                        {'installed_size': 3346,
                                         'packageid': 'com.xrite.i1profiler.sentinel.pkg',
                                         'version': '1.0'},
                                        {'installed_size': 899706,
                                         'packageid': 'com.xrite.i1profiler.i1Profiler.pkg',
                                         'version': '1.0'}],
```
